### ISSUE TITLE
How could you maintain the value in codeaccounts?

### ISSUE THREAD

**Issue by HashDApp** [nsjames/Account-Has-Code#1]
Is the value in codeaccounts always up to date?

**Comment by nsjames** [comment]
Well this is one way https://github.com/nsjames/Account-Has-Code-Watcher ( but it doesn't support inline actions ).

**However, this was a test as a solution for the RAM issue which was a bust.** 
Batches of transactions could make this method useless. 
Check here: https://github.com/EOSEssentials/EOS-Proxy-Token#things-that-didnt-work
